{{
    codegen.generate_source(
        database_name="health",
        schema_name="land_zone",
        generate_columns=True,
        name="stellar",
        include_database=True,
        include_schema=True,
    )
}}
